export type NewsItem = {
  outlet: string
  title: string
  href: string
  category: string
  accent: string
  featured?: boolean
  image: string
}

export function getNewsImage(item: Pick<NewsItem, 'image'>): string | null {
  if (item.image && item.image.trim()) return item.image
  return null
}

export const newsData: NewsItem[] = [
  {
    outlet: "Daily Sun",
    title: "Political Satire Film \"The University of Chankharpul\" Unveils Trailer",
    href: "https://www.daily-sun.com/entertainment/877071/political-satire-film-the-university-of-chankharpul-unveils-trailer",
    category: "PRESS",
    accent: "#e87c1e",
    featured: true,
    image: "/press/link-01.jpg",
  },
  {
    outlet: "Dhaka Tribune",
    title: "Trailer of \"The University of Chankharpul\"",
    href: "https://www.dhakatribune.com/showtime/411199/trailer-of-%E2%80%9Cthe-university-of-chankharpul%E2%80%9D",
    category: "PRESS",
    accent: "#1a6fa8",
    featured: true,
    image: "/press/link-02.jpg",
  },
  {
    outlet: "The Daily Star",
    title: "\"Good Cinema Will Always Find Its Place\" — Akash Haque",
    href: "https://www.thedailystar.net/culture/tv-film/news/good-cinema-will-always-find-its-place-akash-haque-4184886",
    category: "PRESS",
    accent: "#1d7c4d",
    featured: true,
    image: "/press/link-03.jpg",
  },
  {
    outlet: "Nagorik Protidin Online",
    title: "View Full Coverage",
    href: "https://nagorikprotidin.com/entertainment/7679",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-04.jpg",
  },
  {
    outlet: "Chaarcha Online Portal",
    title: "View Full Coverage",
    href: "https://www.chaarcha.com/in-brief/chg7otjdhwca",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-05.jpg",
  },
  {
    outlet: "Jamuna TV",
    title: "View Full Coverage",
    href: "https://jamuna.tv/entertainment/649967",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-06.jpg",
  },
  {
    outlet: "Prothom Alo",
    title: "View Full Coverage",
    href: "https://www.prothomalo.com/entertainment/dhallywood/uorx7yq03m",
    category: "PRESS",
    accent: "#ffd700",
    featured: true,
    image: "/press/link-07.jpg",
  },
  {
    outlet: "Desh TV",
    title: "View Full Coverage",
    href: "https://www.youtube.com/watch?v=fqzhVuTVNiU",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-08.jpg",
  },
  {
    outlet: "Samakal",
    title: "View Full Coverage",
    href: "https://samakal.com/entertainment/article/334364/",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-09.jpg",
  },
  {
    outlet: "The Daily Star",
    title: "View Full Coverage",
    href: "https://www.thedailystar.net/entertainment/tv-film/news/diff-closing-ceremony-university-chankarphul-kurak-among-noted-winners-4084126",
    category: "PRESS",
    accent: "#ffd700",
    featured: true,
    image: "/press/link-10.jpg",
  },
  {
    outlet: "Sara Bangla",
    title: "View Full Coverage",
    href: "https://sarabangla.net/news/post-1111355/",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-11.jpg",
  },
  {
    outlet: "The Daily Star Bangla",
    title: "View Full Coverage",
    href: "https://bangla.thedailystar.net/entertainment/news-732991",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-12.jpg",
  },
  {
    outlet: "Prothom Alo (World Cinema)",
    title: "View Full Coverage",
    href: "https://www.prothomalo.com/entertainment/world-cinema/3nt0y36tpq",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-13.jpg",
  },
  {
    outlet: "Bijoy TV",
    title: "View Full Coverage",
    href: "https://www.youtube.com/watch?v=lenUWovyiik",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-14.jpg",
  },
  {
    outlet: "Kalbela",
    title: "View Full Coverage",
    href: "https://www.kalbela.com/entertainment/dhallywood/258505",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-15.jpg",
  },
  {
    outlet: "Channel i",
    title: "View Full Coverage",
    href: "https://www.channelionline.com/akash-hoque-talks-about-chankharpul/",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-16.jpg",
  },
  {
    outlet: "The Financial Express",
    title: "View Full Coverage",
    href: "https://epaper.thefinancialexpress.com.bd/popUp.php?img_name=2026%2F01%2F21%2Fimages%2F24_100.jpg",
    category: "PRESS",
    accent: "#ffd700",
    featured: true,
    image: "/press/link-17.jpg",
  },
  {
    outlet: "News Trail BD",
    title: "View Full Coverage",
    href: "https://newstrailbd.com/special-exhibition-of-the-university-of-chankharpul-at-alliance-francaise/",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-18.jpg",
  },
  {
    outlet: "Shomoy TV",
    title: "View Full Coverage",
    href: "https://www.somoynews.tv/news/2026-01-22/MVRuvQL4",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-19.jpg",
  },
  {
    outlet: "Independent TV",
    title: "View Full Coverage",
    href: "https://www.itvbd.com/entertainment/dhallywood/254288",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-20.jpg",
  },
  {
    outlet: "Alokito Swadesh",
    title: "View Full Coverage",
    href: "https://alokitoshodesh.com/?p=37178",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-21.jpg",
  },
  {
    outlet: "Banglanews24",
    title: "View Full Coverage",
    href: "https://banglanews24.com/entertainment/news/bd/1632222.details",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-22.jpg",
  },
  {
    outlet: "BDNews24 Bangla",
    title: "View Full Coverage",
    href: "https://bangla.bdnews24.com/glitz/f01d72731604",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-23.jpg",
  },
  {
    outlet: "DigiBangla Tech",
    title: "View Full Coverage",
    href: "https://digibanglatech.news/163710",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-24.jpg",
  },
  {
    outlet: "A1 News 24",
    title: "View Full Coverage",
    href: "https://www.a1news24.com",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-25.jpg",
  },
  {
    outlet: "GNewsBD24",
    title: "View Full Coverage",
    href: "https://gnewsbd24.com/2026/01/15/",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-26.jpg",
  },
  {
    outlet: "Amader Shomoy",
    title: "View Full Coverage",
    href: "https://www.dainikamadershomoy.com/details/019bc16bcfde",
    category: "PRESS",
    accent: "#ffd700",
    image: "/press/link-27.jpg",
  },
  {
    outlet: "The Statesman",
    title: "View Full Coverage",
    href: "https://epaper.thestatesman.com/4117111/Dainik-Statesman/13-TH-FEBRUARY-2026#page/8/1",
    category: "PRESS",
    accent: "#ffd700",
    featured: true,
    image: "/press/link-28.jpg",
  },
]
